name: aab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^8.1.6

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.7.0

  #dateFormat
  intl: ^0.19.0

  #Database
  floor: any

  #make request to api
  retrofit: ^4.4.0

  #Hooks
  flutter_hooks: ^0.20.5

  #chached image
  cached_network_image: ^3.4.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.3.3
  floor_generator: 1.5.0

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/jakarta/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/jakarta/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/jakarta/PlusJakartaSans-Light.ttf
          weight: 300
